### ISSUE TITLE
Semantic markup

### ISSUE THREAD

**Issue by ghost** [markmx3/tea_cozy#2]
https://github.com/markmx3/tea_cozy/blob/master/index.html#L12-L21

Nice job using `header`, `nav`, and `footer` here to make your markup more semantic. 👍 

Try to go the extra mile and add a couple more semantic elements, like: `main`, `section`, `menu`, `figure`, etc. These can all make your markup a lot easier to read and reason about than just using `div`.

**Comment by markmx3** [comment]
Thanks, I didn't think to do that.
