### ISSUE TITLE
Classes and IDs

### ISSUE THREAD

**Issue by ghost** [markmx3/tea_cozy#5]
https://github.com/markmx3/tea_cozy/blob/master/index.html#L39-L86

Nice job using simple but descriptive classes like `teas` and `tea-type` in your teas section. 👍 

Try to do the same for the locations section. Avoid redundant classes like `boxes` and `box` that don't say anything about your site's content. Keep in mind that everything in the DOM is a box, so `box` is a particularly redundant class. The point is to pick something that clearly describes your content and the purpose behind a block of code.

**Comment by markmx3** [comment]
Thank you, very good point.
